#!/usr/bin/env python3
"""skill_digest — precompute the planner's Purpose + Planner-hints digest.

The planner needs only two short sections from each enabled skill's SKILL.md:

  - ``## Purpose``       — for the non-overlap check when selecting skills.
  - ``## Planner hints``  — the scope-gap checklist it works through.

Reading every whole SKILL.md (each 400–850 words) just to pull those two
sections is the planner's single largest avoidable token cost, and it is paid
on *every* plan run. This script extracts them once at ``/agentic-index`` time
into one small file — ``.claude/state/skills_digest.md`` — so the planner reads
that instead of N whole files. Index runs rarely; planning runs per feature, so
the cost moves from per-plan to per-index.

CLI:
  python skill_digest.py build      # (re)write .claude/state/skills_digest.md

The digest is a generated artifact (like vectors.db / project.yml): it lives in
.claude/state/ and must not be hand-edited — re-run /agentic-index to refresh.
"""
from __future__ import annotations

import sys
from pathlib import Path

# Reuse the retriever's config loader so "enabled skills" (incl. the
# enabled_stacks back-compat alias) is resolved identically in both places.
# retriever.py's heavy deps (sqlite_vec / fastembed) are imported lazily inside
# functions, so importing it here does not require them to be installed.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from retriever import CLAUDE_DIR, SKILLS_DIR, load_config  # noqa: E402

DIGEST_PATH = CLAUDE_DIR / "state" / "skills_digest.md"

# Sections the planner actually consumes, in the order they should appear.
WANTED_SECTIONS = ("Purpose", "Planner hints")


def extract_section(text: str, heading: str) -> str | None:
    """Return the body under a ``## <heading>`` level-2 section, or None.

    Captures every line after the heading up to (but not including) the next
    level-2 ``## `` header or end of file. Sub-headers (``### ``) inside the
    section are preserved. Matching on the heading is case-insensitive and
    tolerant of trailing whitespace; deeper/shallower headers do not match.
    """
    target = heading.strip().lower()
    lines = text.splitlines()
    body: list[str] = []
    capturing = False
    for line in lines:
        stripped = line.strip()
        is_h2 = stripped.startswith("## ") and not stripped.startswith("###")
        if is_h2:
            name = stripped[3:].strip().lower()
            if capturing:
                break  # next level-2 section — stop
            if name == target:
                capturing = True
                continue
        elif capturing:
            body.append(line)
    if not capturing:
        return None
    return "\n".join(body).strip() or None


def build_digest(enabled: list[str]) -> tuple[str, list[str]]:
    """Return (digest_markdown, notes) for the given enabled skills."""
    notes: list[str] = []
    enabled_line = ", ".join(enabled) if enabled else "(none)"
    parts: list[str] = [
        "# Skills digest (planner)",
        "",
        "Generated by `/agentic-index` — do not hand-edit; re-run to refresh.",
        "Holds only the `## Purpose` and `## Planner hints` sections the planner",
        "needs, so it reads this one file instead of every skill's whole SKILL.md.",
        "",
        f"Enabled skills: {enabled_line}",
        "",
    ]
    for skill in enabled:
        skill_md = SKILLS_DIR / skill / "SKILL.md"
        if not skill_md.exists():
            # e.g. the "project" pseudo-skill has no SKILL.md — expected.
            notes.append(f"{skill}: no SKILL.md (skipped)")
            continue
        text = skill_md.read_text(encoding="utf-8")
        parts.append(f"## {skill}")
        parts.append("")
        for section in WANTED_SECTIONS:
            parts.append(f"### {section}")
            body = extract_section(text, section)
            if body is None:
                parts.append("(none)")
                if section == "Purpose":
                    # Purpose is required for the non-overlap check — flag it.
                    notes.append(f"{skill}: missing '## Purpose' section")
            else:
                parts.append(body)
            parts.append("")
    return "\n".join(parts).rstrip() + "\n", notes


def main(argv: list[str]) -> int:
    if len(argv) < 2 or argv[1] != "build":
        sys.stderr.write("usage: python skill_digest.py build\n")
        return 2

    cfg = load_config()
    enabled = cfg.get("enabled_skills") or []
    if not enabled:
        sys.stderr.write(
            "[skill_digest] no enabled_skills in .agentic.yml — nothing to digest\n"
        )

    digest, notes = build_digest(enabled)
    DIGEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    DIGEST_PATH.write_text(digest, encoding="utf-8")

    covered = sum(1 for s in enabled if (SKILLS_DIR / s / "SKILL.md").exists())
    print(f"[skill_digest] wrote {DIGEST_PATH} ({covered}/{len(enabled)} skills)")
    for note in notes:
        print(f"[skill_digest] note: {note}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
