#!/usr/bin/env python3
"""Agentic Development Workflow System — installer.

Single-file, cross-platform. Copies the templated `.claude/` tree into the
target project, manages the `# >>> agentic` block in `.gitignore`, and is
fully idempotent. Strips only `_agentic_managed`-marked entries on
`--uninstall`.

Usage (from any directory):
    python <repo>/installer/agentic.py              # install into $PWD
    python <repo>/installer/agentic.py --target <p> # install into <p>
    python <repo>/installer/agentic.py --uninstall  # remove managed entries
    python <repo>/installer/agentic.py --upgrade-config  # merge new template defaults into existing config
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sys
from pathlib import Path

# Windows consoles default to cp1252 and choke on unicode glyphs in print().
try:
    sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
except Exception:
    pass

SCRIPT_DIR = Path(__file__).resolve().parent
TEMPLATES_DIR = SCRIPT_DIR / "templates"

GITIGNORE_BLOCK = """# >>> agentic
# run state is local working memory — durable artifacts are promoted out of it
# (ADRs, docs/features/ dossiers, docs/screenshots/). Review reports may contain
# exploit scenarios — never commit. `**/` also covers nested installs in monorepos.
**/.claude/state/
# bytecode caches dropped by the installed hooks/MCP server at runtime
**/.claude/**/__pycache__/
# per-install record (file hashes + the absolute path this was installed from) —
# machine-specific, regenerated by the installer, read by /agentic-doctor
**/.claude/.install.json
.mcp.json
# <<< agentic
"""
GITIGNORE_RE = re.compile(r"# >>> agentic.*?# <<< agentic\r?\n?", re.DOTALL)

SYSTEM_OWNED = ["agents", "commands", "skills", "hooks", "mcp", "evals", "templates", "state",
                ".agentic.yml", ".install.json"]
# Note: adrs/ is intentionally NOT in SYSTEM_OWNED. ADRs are user-authored
# project decisions; uninstall preserves them. Delete the dir manually if you
# really want them gone.


def info(msg: str) -> None:
    print(f"[agentic] {msg}")


# ---------- install manifest ----------

# Written after every install so an installed project can answer two questions it
# otherwise cannot: "has anyone edited a system file here?" (those edits are
# silently destroyed by the next re-install, since system dirs are mirrored) and
# "is this install behind the template it came from?". Both were guesswork before
# — answering the second took a manual byte-comparison against the source tree,
# and `system_version` cannot help because nothing bumps it.
MANIFEST_NAME = ".install.json"
MIRROR_DIRS = ("agents", "commands", "skills", "hooks", "mcp", "evals", "templates")


def _hash_file(p: Path) -> str:
    import hashlib
    return hashlib.sha256(p.read_bytes()).hexdigest()[:16]


def _source_commit() -> str:
    """The stangent commit these templates came from, if it is a git checkout.

    `system_version` in .agentic.yml has read `1.0.0` since the v3 migration and
    has never been bumped — a hand-maintained version that nobody maintains is
    worse than none, because it looks like information. The commit is derived, so
    it cannot drift, and it answers the question the version was there for:
    exactly which templates is this install running?
    """
    import subprocess
    try:
        r = subprocess.run(["git", "-C", str(SCRIPT_DIR), "rev-parse", "--short", "HEAD"],
                           capture_output=True, text=True, timeout=10)
        if r.returncode == 0 and r.stdout.strip():
            dirty = subprocess.run(["git", "-C", str(SCRIPT_DIR), "status", "--porcelain"],
                                   capture_output=True, text=True, timeout=10)
            suffix = "-dirty" if dirty.stdout.strip() else ""
            return r.stdout.strip() + suffix
    except Exception:
        pass
    return ""


def _template_version() -> str:
    tpl = TEMPLATES_DIR / ".claude" / ".agentic.yml"
    if tpl.exists():
        m = re.search(r"^system_version:\s*(\S+)", tpl.read_text(encoding="utf-8"),
                      re.MULTILINE)
        if m:
            return m.group(1).strip('"').strip("'")
    return "unknown"


def write_manifest(target: Path) -> None:
    """Record what was installed, hashing each system file twice.

    `tpl` is the file as it ships; `cur` is the file on disk after install. They
    differ on purpose for agents — stamp_agent_models rewrites frontmatter per
    project — so a single hash could not tell a local edit from that stamping.
    Two hashes make both questions exact: `cur` drift means someone edited the
    install, `tpl` drift means the source moved on.
    """
    import datetime as _dt
    src = TEMPLATES_DIR / ".claude"
    dst = target / ".claude"
    if not src.exists() or not dst.exists():
        return
    files: dict[str, dict] = {}
    for name in MIRROR_DIRS:
        src_d = src / name
        if not src_d.exists():
            continue
        for f in sorted(src_d.rglob("*")):
            if not f.is_file() or "__pycache__" in f.parts:
                continue
            rel = f.relative_to(src).as_posix()
            installed = dst / rel
            if not installed.is_file():
                continue
            files[rel] = {"tpl": _hash_file(f), "cur": _hash_file(installed)}
    manifest = {
        "system_version": _template_version(),
        "source_commit": _source_commit(),
        "installed_at": _dt.datetime.now(_dt.timezone.utc).isoformat(
            timespec="seconds").replace("+00:00", "Z"),
        "source": str(SCRIPT_DIR),
        "files": files,
    }
    (dst / MANIFEST_NAME).write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    info(f"wrote {MANIFEST_NAME} ({len(files)} system files tracked)")


# ---------- install ----------

def copy_templates(target: Path) -> None:
    """Install templates with mirror semantics for system-owned paths.

    System-owned directories (agents/, commands/, skills/, hooks/, mcp/) are
    fully replaced — any stale files removed in a newer template version
    disappear here too.

    Seed files (.agentic.yml, settings.json, adrs/) are copied only on first
    install. On re-install they are left untouched — they are user config, not
    system code. The user is expected to update them manually when upgrading.

    Everything outside the system-owned set is untouched, so state/ and any
    user-added subdirs survive a re-install.
    """
    src = TEMPLATES_DIR / ".claude"
    if not src.exists():
        raise SystemExit(f"templates not found at {src}")
    dst = target / ".claude"
    dst.mkdir(parents=True, exist_ok=True)

    mirror_dirs = set(MIRROR_DIRS)  # one source of truth; the manifest tracks the same set
    # Seed files: copied on first install only. These are user config — never
    # overwritten so project-specific settings (enabled_skills, MCP servers,
    # hook list) survive a re-install / upgrade.
    seed_files = {".agentic.yml", "settings.json"}
    seed_dirs = {"adrs"}  # copied only on first install; user-managed thereafter

    for name in mirror_dirs:
        src_d = src / name
        if not src_d.exists():
            continue
        dst_d = dst / name
        if dst_d.exists():
            shutil.rmtree(dst_d)
        shutil.copytree(src_d, dst_d)

    for name in seed_files:
        src_f = src / name
        dst_f = dst / name
        if not src_f.exists():
            continue
        if dst_f.exists():
            info(f"{name} already present — leaving as-is (edit manually to pick up new defaults)")
        else:
            shutil.copy2(src_f, dst_f)
            info(f"seeded {name}")

    for name in seed_dirs:
        src_d = src / name
        dst_d = dst / name
        if not src_d.exists():
            continue
        if dst_d.exists():
            info(f"seed dir {name}/ already present — leaving as-is")
            continue
        shutil.copytree(src_d, dst_d)

    # .mcp.json — Claude Desktop reads this at project root (not under .claude/).
    # Seeded only on first install so user-added credentials survive re-install.
    mcp_src = TEMPLATES_DIR / ".mcp.json"
    mcp_dst = target / ".mcp.json"
    if mcp_src.exists():
        if mcp_dst.exists():
            info(".mcp.json already present at project root — leaving as-is")
        else:
            shutil.copy2(mcp_src, mcp_dst)
            info("seeded .mcp.json at project root — fill in DSN + PAT to enable dbhub/supabase")

    info(f"copied templates to {dst}")


def add_gitignore_block(target: Path) -> None:
    gi = target / ".gitignore"
    if gi.exists():
        content = gi.read_text(encoding="utf-8")
        if "# >>> agentic" in content:
            # Refresh the managed block in place so re-installs pick up new
            # ignore rules (e.g. review-report dirs). The block is delimited and
            # installer-owned; anything outside it is left untouched.
            if GITIGNORE_BLOCK.strip() in content:
                info(".gitignore agentic block already current")
                return
            content = GITIGNORE_RE.sub("", content).rstrip("\n")
            sep = "\n\n" if content else ""
            gi.write_text(content + sep + GITIGNORE_BLOCK, encoding="utf-8")
            info("refreshed .gitignore agentic block")
            return
        sep = "" if content.endswith("\n") else "\n"
        gi.write_text(content + sep + "\n" + GITIGNORE_BLOCK, encoding="utf-8")
    else:
        gi.write_text(GITIGNORE_BLOCK, encoding="utf-8")
    info("wrote .gitignore agentic block")


def sync_managed_hooks(target: Path) -> None:
    """Keep `_agentic_managed` hooks in the project's settings.json current with the
    template. settings.json is seed-once, so without this a NEW managed hook (e.g.
    a new SubagentStop telemetry hook) would never reach existing installs. Only
    managed entries are added; user hooks and all other settings are preserved.
    Idempotent — matches by command string."""
    tpl_path = TEMPLATES_DIR / ".claude" / "settings.json"
    dst_path = target / ".claude" / "settings.json"
    if not tpl_path.exists() or not dst_path.exists():
        return
    try:
        tpl = json.loads(tpl_path.read_text(encoding="utf-8"))
        dst = json.loads(dst_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        info(f"warning: could not parse settings.json: {e} — skipping hook sync")
        return

    def _script(cmd: str) -> str:
        # Identify a managed hook by its .py script, NOT the full command — the
        # command format has drifted across versions (e.g. a `${CLAUDE_PROJECT_DIR}`
        # prefix vs a plain relative path), and matching on the whole string would
        # add a duplicate of a hook that is already installed.
        m = re.search(r"([\w.-]+\.py)", cmd or "")
        return m.group(1) if m else (cmd or "")

    dst_hooks = dst.setdefault("hooks", {})
    added = []
    for event, tpl_entries in (tpl.get("hooks") or {}).items():
        dst_entries = dst_hooks.setdefault(event, [])
        existing = {
            _script(h.get("command"))
            for entry in dst_entries for h in entry.get("hooks", [])
            if h.get("_agentic_managed")
        }
        for entry in tpl_entries:
            for h in entry.get("hooks", []):
                if not h.get("_agentic_managed") or _script(h.get("command")) in existing:
                    continue
                new_entry = {"hooks": [h]}
                if entry.get("matcher") is not None:
                    new_entry = {"matcher": entry["matcher"], "hooks": [h]}
                dst_entries.append(new_entry)
                existing.add(_script(h.get("command")))
                added.append(f"{event}:{h.get('command')}")
    if added:
        dst_path.write_text(json.dumps(dst, indent=2) + "\n", encoding="utf-8")
        info(f"settings.json: synced managed hooks ({len(added)} added)")


def _parse_models(agentic_yml_text: str) -> dict:
    """Parse the `models:` block of .agentic.yml with a line reader (no PyYAML,
    which the installer does not depend on). Returns {role: model_id}, skipping
    empty values (role: "" means 'inherit the session default')."""
    out: dict[str, str] = {}
    in_block = False
    for line in agentic_yml_text.splitlines():
        if re.match(r"^models:\s*(#.*)?$", line):
            in_block = True
            continue
        if in_block:
            if line and not line[0].isspace():  # dedent → block ended
                break
            m = re.match(r"^\s+([\w-]+):\s*(\S*)", line)
            if m:
                # Keep empty values too: role: "" means "inherit session default"
                # (don't stamp), which is distinct from a role being absent.
                out[m.group(1)] = m.group(2).strip('"').strip("'")
    return out


def _set_frontmatter_model(text: str, model: str) -> str:
    """Set/replace `model:` in a Markdown agent's YAML frontmatter."""
    m = re.match(r"(?s)^(---\n)(.*?\n)(---\n)", text)
    if not m:
        return text  # no frontmatter — leave untouched
    head, fm, tail = m.group(1), m.group(2), m.group(3)
    rest = text[m.end():]
    if re.search(r"(?m)^model:\s*.*$", fm):
        fm = re.sub(r"(?m)^model:\s*.*$", f"model: {model}", fm, count=1)
    elif re.search(r"(?m)^name:\s*.*$", fm):
        fm = re.sub(r"(?m)^(name:.*)$", r"\1\nmodel: " + model, fm, count=1)
    else:
        fm = f"model: {model}\n" + fm
    return head + fm + tail + rest


def stamp_agent_models(target: Path) -> None:
    """Write each agent's configured model into its frontmatter from .agentic.yml.

    Claude Desktop honors a subagent's frontmatter `model:` but IGNORES the
    invocation-time model override that dispatch_plan.py relies on — so without
    this every agent runs on the session model there, not its configured role
    model. Stamping makes Desktop honor role models. In the CLI, an explicit
    invocation model (complexity routing) still overrides frontmatter, so dynamic
    per-task routing is preserved. .agentic.yml stays the single source of truth;
    templates ship model-agnostic and this derives the frontmatter per install."""
    ayml = target / ".claude" / ".agentic.yml"
    agents_dir = target / ".claude" / "agents"
    if not ayml.exists() or not agents_dir.is_dir():
        return
    models = _parse_models(ayml.read_text(encoding="utf-8"))
    if not models:
        return
    default = models.get("default", "")
    stamped = 0
    for md in sorted(agents_dir.glob("*.md")):
        # explicit role entry wins (incl. "" = inherit → skip); else the default
        model = models[md.stem] if md.stem in models else default
        if not model:  # "" → inherit session default; don't pin a model
            continue
        text = md.read_text(encoding="utf-8")
        updated = _set_frontmatter_model(text, model)
        if updated != text:
            md.write_text(updated, encoding="utf-8")
            stamped += 1
    if stamped:
        info(f"stamped model: into {stamped} agent frontmatter(s) from .agentic.yml models:")


def _merge_missing_section_keys(target: Path, section: str, keys: tuple[str, ...]) -> None:
    """Back-fill keys the template adds INSIDE an existing top-level block
    (e.g. `never_downgrade:` under `complexity_routing:`).

    The section-level upgrade only appends blocks that are absent wholesale, so a
    project seeded before a key existed keeps an outdated policy forever and
    silently. That matters for `never_downgrade`: without it, `low_cap` pulls
    gate-owning reviewers back down to the cheapest model on low-complexity
    tasks — the exact regression the key was added to prevent. For keys whose
    absent-default is already correct (`git.checkpoint_commits`) this is about
    discoverability: the behavior is right either way, but a key you cannot see
    in your own config is one you cannot turn off."""
    tpl_path = TEMPLATES_DIR / ".claude" / ".agentic.yml"
    dst_path = target / ".claude" / ".agentic.yml"
    if not tpl_path.exists() or not dst_path.exists():
        return
    tpl_text = tpl_path.read_text(encoding="utf-8")
    dst_text = dst_path.read_text(encoding="utf-8")
    lines = dst_text.splitlines(keepends=True)
    start = next((i for i, l in enumerate(lines)
                  if re.match(rf"^{re.escape(section)}:\s*(#.*)?$", l)), None)
    if start is None:
        return  # no block at all — the section-level append handles that case
    end = start
    for i in range(start + 1, len(lines)):
        if lines[i].strip() == "" or lines[i][:1].isspace():
            end = i
        else:
            break
    block = "".join(lines[start:end + 1])

    added = []
    for key in keys:
        if re.search(rf"^\s+{key}:", block, re.MULTILINE):
            continue
        m = re.search(rf"^(\s+{key}:.*)$", tpl_text, re.MULTILINE)
        if m:
            lines.insert(end + 1, m.group(1) + "\n")
            end += 1
            added.append(key)
    if added:
        dst_path.write_text("".join(lines), encoding="utf-8")
        info(f".agentic.yml: added missing {section} keys: {', '.join(added)}")


def _merge_missing_model_keys(target: Path) -> None:
    """Add role→model entries the template defines but the project's models: block
    is missing (e.g. roles added after the project was seeded), without touching
    the user's existing values. Fixes seed-once drift that would otherwise leave
    newer roles falling back to `default`."""
    tpl_path = TEMPLATES_DIR / ".claude" / ".agentic.yml"
    dst_path = target / ".claude" / ".agentic.yml"
    if not tpl_path.exists() or not dst_path.exists():
        return
    tpl_models = _parse_models(tpl_path.read_text(encoding="utf-8"))
    dst_text = dst_path.read_text(encoding="utf-8")
    dst_models = _parse_models(dst_text)
    missing = {k: v for k, v in tpl_models.items() if k not in dst_models}
    if not missing:
        return
    lines = dst_text.splitlines(keepends=True)
    start = next((i for i, l in enumerate(lines) if re.match(r"^models:\s*(#.*)?$", l)), None)
    if start is None:
        return
    last = start  # index of the last indented line in the models: block
    for i in range(start + 1, len(lines)):
        if lines[i].strip() == "":
            continue
        if lines[i][:1].isspace():
            last = i
        else:
            break
    ins = "".join(f"  {k}: {v}\n" for k, v in missing.items())
    dst_path.write_text("".join(lines[:last + 1]) + ins + "".join(lines[last + 1:]), encoding="utf-8")
    info(f".agentic.yml: added missing model roles: {', '.join(missing)}")


def install(target: Path) -> None:
    target.mkdir(parents=True, exist_ok=True)
    copy_templates(target)
    sync_managed_hooks(target)
    stamp_agent_models(target)
    write_manifest(target)  # after stamping — `cur` must hash the final files
    add_gitignore_block(target)
    info(f"install complete at {target}")
    info("next: pip install pyyaml fastembed sqlite-vec")
    info("then in Claude Code: /agentic-index  ->  /agentic-plan <goal>  ->  /agentic-build all")


# ---------- uninstall ----------

def strip_managed_settings(target: Path) -> None:
    p = target / ".claude" / "settings.json"
    if not p.exists():
        return
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        info(f"warning: could not parse {p}; leaving untouched")
        return

    hooks = data.get("hooks", {})
    for ev in list(hooks.keys()):
        kept = []
        for entry in hooks[ev]:
            new_hooks = [h for h in entry.get("hooks", []) if not h.get("_agentic_managed")]
            if new_hooks:
                entry["hooks"] = new_hooks
                kept.append(entry)
        if kept:
            hooks[ev] = kept
        else:
            del hooks[ev]
    if not hooks:
        data.pop("hooks", None)

    mcp = data.get("mcpServers", {})
    for name in list(mcp.keys()):
        if mcp[name].get("_agentic_managed"):
            del mcp[name]
    if not mcp:
        data.pop("mcpServers", None)

    if not data:
        p.unlink()
        info("removed empty settings.json")
    else:
        p.write_text(json.dumps(data, indent=2), encoding="utf-8")
        info("stripped managed entries from settings.json")


def remove_mcp_json_if_template(target: Path) -> None:
    """Remove .mcp.json only if it still looks like the unedited template
    (contains the REPLACE_WITH_... placeholders). If the user has filled
    in real credentials, we leave it alone."""
    p = target / ".mcp.json"
    if not p.exists():
        return
    content = p.read_text(encoding="utf-8")
    if "REPLACE_WITH_" in content:
        p.unlink()
        info("removed .mcp.json (was unedited template)")
    else:
        info(".mcp.json kept — contains real credentials. Delete manually if you want it gone.")


def remove_system_dirs(target: Path) -> None:
    claude = target / ".claude"
    if not claude.exists():
        return
    for name in SYSTEM_OWNED:
        p = claude / name
        if p.is_file():
            p.unlink()
            info(f"removed {name}")
        elif p.is_dir():
            shutil.rmtree(p)
            info(f"removed {name}/")
    if not any(claude.iterdir()):
        claude.rmdir()
        info("removed empty .claude/")


def remove_gitignore_block(target: Path) -> None:
    gi = target / ".gitignore"
    if not gi.exists():
        return
    new = GITIGNORE_RE.sub("", gi.read_text(encoding="utf-8"))
    if new.strip() == "":
        gi.unlink()
        info("removed empty .gitignore")
    else:
        gi.write_text(new, encoding="utf-8")
        info("stripped agentic block from .gitignore")


def uninstall(target: Path) -> None:
    strip_managed_settings(target)
    remove_system_dirs(target)
    remove_mcp_json_if_template(target)
    remove_gitignore_block(target)
    info(f"uninstall complete at {target}")


# ---------- upgrade-config ----------

def _upgrade_settings_json(target: Path) -> None:
    """Add new enabledMcpjsonServers entries from template; leave existing entries alone."""
    tpl_path = TEMPLATES_DIR / ".claude" / "settings.json"
    dst_path = target / ".claude" / "settings.json"
    if not tpl_path.exists() or not dst_path.exists():
        return
    try:
        tpl = json.loads(tpl_path.read_text(encoding="utf-8"))
        dst = json.loads(dst_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        info(f"warning: could not parse settings.json: {e} — skipping")
        return

    changed = False

    tpl_servers = tpl.get("enabledMcpjsonServers", [])
    dst_servers = dst.get("enabledMcpjsonServers", [])
    new_servers = [s for s in tpl_servers if s not in dst_servers]
    if new_servers:
        dst["enabledMcpjsonServers"] = dst_servers + new_servers
        changed = True
        info(f"settings.json: added to enabledMcpjsonServers: {new_servers}")

    if changed:
        dst_path.write_text(json.dumps(dst, indent=2) + "\n", encoding="utf-8")
    else:
        info("settings.json: already up to date")


def _upgrade_mcp_json(target: Path) -> None:
    """Add new mcpServers entries from template; leave existing entries alone."""
    tpl_path = TEMPLATES_DIR / ".mcp.json"
    dst_path = target / ".mcp.json"
    if not tpl_path.exists() or not dst_path.exists():
        return
    try:
        tpl = json.loads(tpl_path.read_text(encoding="utf-8"))
        dst = json.loads(dst_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        info(f"warning: could not parse .mcp.json: {e} — skipping")
        return

    tpl_servers = tpl.get("mcpServers", {})
    dst_servers = dst.get("mcpServers", {})

    added = []
    for name, config in tpl_servers.items():
        # Skip JSON comment/divider entries (string values, not server objects).
        if not isinstance(config, dict):
            continue
        if name not in dst_servers:
            dst_servers[name] = config
            added.append(name)

    if added:
        dst["mcpServers"] = dst_servers
        # Refresh the top-level comment so it stays accurate.
        if "_comment" in tpl:
            dst["_comment"] = tpl["_comment"]
        dst_path.write_text(json.dumps(dst, indent=2) + "\n", encoding="utf-8")
        info(f".mcp.json: added servers: {added}")
    else:
        info(".mcp.json: already up to date")


def _upgrade_agentic_yml(target: Path) -> None:
    """Replace only the available-skills comment block in .agentic.yml.

    Everything else (enabled_skills, embedding, gateway, etc.) is untouched
    because those are user configuration, not documentation.
    """
    tpl_path = TEMPLATES_DIR / ".claude" / ".agentic.yml"
    dst_path = target / ".claude" / ".agentic.yml"
    if not tpl_path.exists() or not dst_path.exists():
        return

    # Match from any comment line containing "Available built-in skills:" through
    # all subsequent comment lines, stopping just before "enabled_skills:".
    block_re = re.compile(r"(#[^\n]*Available built-in skills:[^\n]*\n(?:#[^\n]*\n)*)(?=enabled_skills:)", re.DOTALL)

    tpl_text = tpl_path.read_text(encoding="utf-8")
    dst_text = dst_path.read_text(encoding="utf-8")

    tpl_m = block_re.search(tpl_text)
    dst_m = block_re.search(dst_text)

    if not tpl_m:
        return
    if not dst_m:
        info(".agentic.yml: skills comment block not found (file may be customized) — skipping; add rest-openapi to the backend list manually if needed")
    elif tpl_m.group(1) == dst_m.group(1):
        info(".agentic.yml: skills block already up to date")
    else:
        dst_text = dst_text[: dst_m.start(1)] + tpl_m.group(1) + dst_text[dst_m.end(1):]
        dst_path.write_text(dst_text, encoding="utf-8")
        info(".agentic.yml: updated available-skills comment block")

    # Append the models: section if it doesn't exist yet (independent of the skills block).
    dst_text = dst_path.read_text(encoding="utf-8")
    if "models:" not in dst_text:
        models_block_re = re.compile(r"^models:.*?(?=^\w|\Z)", re.DOTALL | re.MULTILINE)
        tpl_m2 = models_block_re.search(tpl_text)
        if tpl_m2:
            dst_path.write_text(dst_text.rstrip() + "\n\n" + tpl_m2.group(0).rstrip() + "\n", encoding="utf-8")
            info(".agentic.yml: added models: section")

    # Append the complexity_routing: section if it doesn't exist yet.
    dst_text = dst_path.read_text(encoding="utf-8")
    if "complexity_routing:" not in dst_text:
        cr_re = re.compile(r"^complexity_routing:.*?(?=^\w|\Z)", re.DOTALL | re.MULTILINE)
        tpl_cr = cr_re.search(tpl_text)
        if tpl_cr:
            dst_path.write_text(dst_text.rstrip() + "\n\n" + tpl_cr.group(0).rstrip() + "\n", encoding="utf-8")
            info(".agentic.yml: added complexity_routing: section")

    # Append the model_capability_order: section if it doesn't exist yet
    # (dispatch_plan.py falls back to a built-in ladder, but adding it here lets
    # users rank newer model IDs).
    dst_text = dst_path.read_text(encoding="utf-8")
    if "model_capability_order:" not in dst_text:
        mco_re = re.compile(r"^model_capability_order:.*?(?=^\w|\Z)", re.DOTALL | re.MULTILINE)
        tpl_mco = mco_re.search(tpl_text)
        if tpl_mco:
            dst_path.write_text(dst_text.rstrip() + "\n\n" + tpl_mco.group(0).rstrip() + "\n", encoding="utf-8")
            info(".agentic.yml: added model_capability_order: section")

    # Append the maestro: section if it doesn't exist yet.
    dst_text = dst_path.read_text(encoding="utf-8")
    if "maestro:" not in dst_text:
        maestro_re = re.compile(r"^maestro:.*?(?=^\w|\Z)", re.DOTALL | re.MULTILINE)
        tpl_maestro = maestro_re.search(tpl_text)
        if tpl_maestro:
            dst_path.write_text(dst_text.rstrip() + "\n\n" + tpl_maestro.group(0).rstrip() + "\n", encoding="utf-8")
            info(".agentic.yml: added maestro: section")


def upgrade_config(target: Path) -> None:
    _upgrade_settings_json(target)
    _upgrade_mcp_json(target)
    _upgrade_agentic_yml(target)
    _merge_missing_model_keys(target)    # heal seed-once drift in models: block
    _merge_missing_section_keys(target, "complexity_routing", ("never_downgrade",))
    _merge_missing_section_keys(target, "git", ("checkpoint_commits",))
    stamp_agent_models(target)           # re-apply role models after the merge/edit
    write_manifest(target)               # …and re-record, since stamping may have changed files
    info(f"upgrade-config complete at {target}")


# ---------- cli ----------

def main() -> None:
    ap = argparse.ArgumentParser(description="Agentic Development Workflow installer.")
    ap.add_argument("--target", default=os.getcwd(), help="Project directory (default: cwd).")
    ap.add_argument("--uninstall", action="store_true", help="Remove managed entries.")
    ap.add_argument(
        "--upgrade-config",
        action="store_true",
        help="Merge new template defaults into existing config files "
             "(settings.json, .mcp.json, .agentic.yml). "
             "Adds new keys; never overwrites existing values.",
    )
    args = ap.parse_args()

    target = Path(args.target).resolve()
    if args.uninstall:
        uninstall(target)
    elif getattr(args, "upgrade_config"):
        upgrade_config(target)
    else:
        install(target)


if __name__ == "__main__":
    main()
