#!/usr/bin/env python3
"""Agentic Development Workflow System — installer.

Single-file, cross-platform. Copies the templated `.claude/` tree into the
target project, manages the `# >>> agentic` block in `.gitignore`, and is
fully idempotent. Strips only `_agentic_managed`-marked entries on
`--uninstall`.

Usage (from any directory):
    python <repo>/installer/agentic.py              # install into $PWD
    python <repo>/installer/agentic.py --target <p> # install into <p>
    python <repo>/installer/agentic.py --uninstall  # remove managed entries
    python <repo>/installer/agentic.py --upgrade-config  # merge new template defaults into existing config
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sys
from pathlib import Path

# Windows consoles default to cp1252 and choke on unicode glyphs in print().
try:
    sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
except Exception:
    pass

SCRIPT_DIR = Path(__file__).resolve().parent
TEMPLATES_DIR = SCRIPT_DIR / "templates"

# `.mcp.json` is appended to this block ONLY when the project's own file still
# holds plaintext credentials — see mcp_json_holds_secret(). The template ships
# ${VAR} expansion so a fresh install has nothing to hide and the file is
# committed like the rest of .claude/; but a project installed before that change
# has a real token sitting in it, and silently un-ignoring the file would stage
# the token on the owner's next `git add -A`.
GITIGNORE_BLOCK = """# >>> agentic
# run state is local working memory — durable artifacts are promoted out of it
# (ADRs, docs/features/ dossiers, docs/screenshots/). Review reports may contain
# exploit scenarios — never commit. `**/` also covers nested installs in monorepos.
**/.claude/state/
# bytecode caches dropped by the installed hooks/MCP server at runtime
**/.claude/**/__pycache__/
# per-install record (file hashes + the absolute path this was installed from) —
# machine-specific, regenerated by the installer, read by /agentic-doctor
**/.claude/.install.json
# .mcp.json is deliberately NOT ignored: it carries no secrets (credentials come
# from ${VAR} in the environment), so server config is reviewable in PRs like the
# rest of .claude/.
# .claude/tests/ is deliberately NOT ignored either. It is the record of what has
# actually been verified, and its run history is what tells a red case apart from
# one that was never green. Ignore it and every fresh clone starts with no
# regression baseline at all.
# <<< agentic
"""
GITIGNORE_RE = re.compile(r"# >>> agentic.*?# <<< agentic\r?\n?", re.DOTALL)

SYSTEM_OWNED = ["agents", "commands", "skills", "hooks", "mcp", "evals", "templates",
                "py", ".agentic.yml", ".install.json"]
# Note: adrs/, tests/ and state/ are intentionally NOT in SYSTEM_OWNED, for
# different reasons. ADRs are user-authored project decisions. tests/ holds the
# registered regression cases — the record of what has actually been verified,
# which no reinstall should be able to erase. state/ is every plan, run log and
# vectors.db — gitignored, so deleting it is unrecoverable, and it made
# `--uninstall` a data-loss operation contradicting the README's promise that
# "anything you added is left alone". Keeping it also means uninstall can be run
# safely as a step toward reinstalling. All are reported and left in place.


def info(msg: str) -> None:
    print(f"[agentic] {msg}")


# ---------- install manifest ----------

# Written after every install so an installed project can answer two questions it
# otherwise cannot: "has anyone edited a system file here?" (those edits are
# silently destroyed by the next re-install, since system dirs are mirrored) and
# "is this install behind the template it came from?". Both were guesswork before
# — answering the second took a manual byte-comparison against the source tree.
MANIFEST_NAME = ".install.json"
MIRROR_DIRS = ("agents", "commands", "skills", "hooks", "mcp", "evals", "templates")

# Tool caches that appear in the template tree whenever anyone runs the suite or
# a linter from this checkout. They are gitignored here, so they never reach a
# clone — but the installer copies from the WORKING TREE, which mirrored one
# developer's local caches into every install and then tracked them in
# .install.json as system files. Observed: 12 such dirs in a real install.
COPY_IGNORE = ("__pycache__", "*.pyc", ".pytest_cache", ".ruff_cache", ".DS_Store")
# The directory names among those, for filtering a walk rather than a copy.
_CACHE_DIRS = frozenset(n for n in COPY_IGNORE if not n.startswith("*") and n != ".DS_Store")


def _is_cache_path(p: Path) -> bool:
    """True for tool-cache droppings, wherever they sit in the tree.

    `write_manifest` filtered only `__pycache__`, so `.pytest_cache` files were
    hashed and recorded as system files — which then read as install content that
    a re-install would legitimately replace."""
    return bool(_CACHE_DIRS.intersection(p.parts)) or p.name == ".DS_Store" \
        or p.suffix == ".pyc"


def _hash_file(p: Path) -> str:
    import hashlib
    return hashlib.sha256(p.read_bytes()).hexdigest()[:16]


def _source_commit() -> str:
    """The stangent commit these templates came from, if it is a git checkout.

    This replaced a hand-maintained `system_version` that had read `1.0.0` since
    the v3 migration — a version nobody bumps is worse than none, because it
    looks like information. The commit is derived, so it cannot drift, and it
    answers the question the version was there for: exactly which templates is
    this install running?
    """
    import subprocess
    try:
        r = subprocess.run(["git", "-C", str(SCRIPT_DIR), "rev-parse", "--short", "HEAD"],
                           capture_output=True, text=True, timeout=10)
        if r.returncode == 0 and r.stdout.strip():
            dirty = subprocess.run(["git", "-C", str(SCRIPT_DIR), "status", "--porcelain"],
                                   capture_output=True, text=True, timeout=10)
            suffix = "-dirty" if dirty.stdout.strip() else ""
            return r.stdout.strip() + suffix
    except Exception:
        pass
    return ""


def write_manifest(target: Path) -> None:
    """Record what was installed, hashing each system file twice.

    `tpl` is the file as it ships; `cur` is the file on disk after install. They
    differ on purpose for agents — stamp_agent_models rewrites frontmatter per
    project — so a single hash could not tell a local edit from that stamping.
    Two hashes make both questions exact: `cur` drift means someone edited the
    install, `tpl` drift means the source moved on.
    """
    import datetime as _dt
    src = TEMPLATES_DIR / ".claude"
    dst = target / ".claude"
    if not src.exists() or not dst.exists():
        return
    files: dict[str, dict] = {}
    for name in MIRROR_DIRS:
        src_d = src / name
        if not src_d.exists():
            continue
        for f in sorted(src_d.rglob("*")):
            if not f.is_file() or _is_cache_path(f):
                continue
            rel = f.relative_to(src).as_posix()
            installed = dst / rel
            if not installed.is_file():
                continue
            files[rel] = {"tpl": _hash_file(f), "cur": _hash_file(installed)}
    manifest = {
        "source_commit": _source_commit(),
        "installed_at": _dt.datetime.now(_dt.timezone.utc).isoformat(
            timespec="seconds").replace("+00:00", "Z"),
        "source": str(SCRIPT_DIR),
        "files": files,
    }
    (dst / MANIFEST_NAME).write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    info(f"wrote {MANIFEST_NAME} ({len(files)} system files tracked)")


# ---------- install ----------

def copy_templates(target: Path) -> None:
    """Install templates with mirror semantics for system-owned paths.

    System-owned directories (agents/, commands/, skills/, hooks/, mcp/) are
    fully replaced — any stale files removed in a newer template version
    disappear here too.

    Seed files (.agentic.yml, settings.json, adrs/) are copied only on first
    install. On re-install they are left untouched — they are user config, not
    system code. The user is expected to update them manually when upgrading.

    Everything outside the system-owned set is untouched, so state/ and any
    user-added subdirs survive a re-install.
    """
    src = TEMPLATES_DIR / ".claude"
    if not src.exists():
        raise SystemExit(f"templates not found at {src}")
    dst = target / ".claude"
    dst.mkdir(parents=True, exist_ok=True)

    mirror_dirs = set(MIRROR_DIRS)  # one source of truth; the manifest tracks the same set
    # Seed files: copied on first install only. These are user config — never
    # overwritten so project-specific settings (enabled_skills, MCP servers,
    # hook list) survive a re-install / upgrade.
    seed_files = {".agentic.yml", "settings.json"}
    # Seed dirs: copied only on first install; user-managed thereafter.
    # `tests/` holds the project's registered regression cases — mirroring it
    # would delete every case on the next upgrade.
    seed_dirs = {"adrs", "tests"}

    for name in mirror_dirs:
        src_d = src / name
        if not src_d.exists():
            continue
        dst_d = dst / name
        if dst_d.exists():
            shutil.rmtree(dst_d)
        shutil.copytree(src_d, dst_d, ignore=shutil.ignore_patterns(*COPY_IGNORE))

    for name in seed_files:
        src_f = src / name
        dst_f = dst / name
        if not src_f.exists():
            continue
        if dst_f.exists():
            info(f"{name} already present — leaving as-is (edit manually to pick up new defaults)")
        else:
            shutil.copy2(src_f, dst_f)
            info(f"seeded {name}")

    for name in seed_dirs:
        src_d = src / name
        dst_d = dst / name
        if not src_d.exists():
            continue
        if dst_d.exists():
            info(f"seed dir {name}/ already present — leaving as-is")
            continue
        shutil.copytree(src_d, dst_d)

    # `py` — the interpreter resolver every command goes through. Mirrored (not
    # seeded) so a fix to it reaches existing installs, and copied with its exec
    # bit intact. Commands invoke it as `sh .claude/py`, so the bit is a
    # convenience rather than a requirement.
    py_src = src / "py"
    if py_src.exists():
        py_dst = dst / "py"
        shutil.copy2(py_src, py_dst)
        try:
            py_dst.chmod(py_dst.stat().st_mode | 0o111)
        except OSError:
            pass  # Windows filesystems have no exec bit; `sh .claude/py` still works

    # .mcp.json — Claude Desktop reads this at project root (not under .claude/).
    # Seeded only on first install so user-added credentials survive re-install.
    mcp_src = TEMPLATES_DIR / ".mcp.json"
    mcp_dst = target / ".mcp.json"
    if mcp_src.exists():
        if mcp_dst.exists():
            info(".mcp.json already present at project root — leaving as-is")
        else:
            shutil.copy2(mcp_src, mcp_dst)
            info("seeded .mcp.json at project root — fill in DSN + PAT to enable dbhub/supabase")

    info(f"copied templates to {dst}")


# Flags whose value is a credential, and env keys that name one.
_SECRET_FLAGS = ("--access-token", "--dsn", "--project-ref", "--api-key", "--token")
_SECRET_ENV_RE = re.compile(r"(TOKEN|KEY|SECRET|PASSWORD|DSN|PAT)$", re.IGNORECASE)
_PLACEHOLDER_RE = re.compile(r"^(REPLACE_WITH_|OPTIONAL_|\$\{)")


def mcp_json_holds_secret(target: Path) -> bool:
    """True if .mcp.json carries a credential as a literal rather than ${VAR}.

    Decides whether the file may be un-ignored. A fresh install cannot trip this
    — the template uses ${VAR} throughout — but a project installed before that
    change has a live token in the file, and it is gitignored for that reason.
    Refreshing the managed block without checking would remove that protection
    and stage the token on the next `git add -A`.
    """
    p = target / ".mcp.json"
    if not p.is_file():
        return False
    try:
        cfg = json.loads(p.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return True  # unreadable: assume the worst and keep ignoring it
    for srv in (cfg.get("mcpServers") or {}).values():
        if not isinstance(srv, dict):
            continue
        args = [str(a) for a in srv.get("args") or []]
        for flag in _SECRET_FLAGS:
            if flag in args:
                i = args.index(flag)
                if i + 1 < len(args) and not _PLACEHOLDER_RE.match(args[i + 1]):
                    return True
        for k, v in (srv.get("env") or {}).items():
            if _SECRET_ENV_RE.search(k) and not _PLACEHOLDER_RE.match(str(v)):
                return True
    return False


def gitignore_block_for(target: Path) -> str:
    block = GITIGNORE_BLOCK
    if mcp_json_holds_secret(target):
        # Replace the "not ignored" rationale rather than appending after it —
        # leaving both makes the committed .gitignore contradict itself.
        block = block.replace(
            "# .mcp.json is deliberately NOT ignored: it carries no secrets (credentials come\n"
            "# from ${VAR} in the environment), so server config is reviewable in PRs like the\n"
            "# rest of .claude/.\n",
            "# this project's .mcp.json still holds a credential in plaintext, so it stays\n"
            "# ignored. Switch those entries to ${VAR} expansion and re-run the installer to\n"
            "# commit it alongside the rest of .claude/.\n.mcp.json\n")
    return block


def add_gitignore_block(target: Path) -> None:
    gi = target / ".gitignore"
    if gi.exists():
        content = gi.read_text(encoding="utf-8")
        if "# >>> agentic" in content:
            # Refresh the managed block in place so re-installs pick up new
            # ignore rules (e.g. review-report dirs). The block is delimited and
            # installer-owned; anything outside it is left untouched.
            block = gitignore_block_for(target)
            if block.strip() in content:
                info(".gitignore agentic block already current")
                return
            content = GITIGNORE_RE.sub("", content).rstrip("\n")
            sep = "\n\n" if content else ""
            gi.write_text(content + sep + block, encoding="utf-8")
            if mcp_json_holds_secret(target):
                info("kept .mcp.json gitignored — it still holds a plaintext "
                     "credential; switch it to ${VAR} expansion to commit it")
            info("refreshed .gitignore agentic block")
            return
        sep = "" if content.endswith("\n") else "\n"
        gi.write_text(content + sep + "\n" + gitignore_block_for(target), encoding="utf-8")
    else:
        gi.write_text(gitignore_block_for(target), encoding="utf-8")
    info("wrote .gitignore agentic block")


def sync_managed_hooks(target: Path) -> None:
    """Keep `_agentic_managed` hooks in the project's settings.json current with the
    template. settings.json is seed-once, so without this a NEW managed hook (e.g.
    a new SubagentStop telemetry hook) would never reach existing installs. Only
    managed entries are added; user hooks and all other settings are preserved.
    Idempotent — matches by command string."""
    tpl_path = TEMPLATES_DIR / ".claude" / "settings.json"
    dst_path = target / ".claude" / "settings.json"
    if not tpl_path.exists() or not dst_path.exists():
        return
    try:
        tpl = json.loads(tpl_path.read_text(encoding="utf-8"))
        dst = json.loads(dst_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        info(f"warning: could not parse settings.json: {e} — skipping hook sync")
        return

    def _script(cmd: str) -> str:
        # Identify a managed hook by its .py script, NOT the full command — the
        # command format has drifted across versions (e.g. a `${CLAUDE_PROJECT_DIR}`
        # prefix vs a plain relative path), and matching on the whole string would
        # add a duplicate of a hook that is already installed.
        m = re.search(r"([\w.-]+\.py)", cmd or "")
        return m.group(1) if m else (cmd or "")

    dst_hooks = dst.setdefault("hooks", {})
    added: list[str] = []
    updated: list[str] = []
    for event, tpl_entries in (tpl.get("hooks") or {}).items():
        dst_entries = dst_hooks.setdefault(event, [])
        existing = {
            _script(h.get("command")): h
            for entry in dst_entries for h in entry.get("hooks", [])
            if h.get("_agentic_managed")
        }
        for entry in tpl_entries:
            for h in entry.get("hooks", []):
                if not h.get("_agentic_managed"):
                    continue
                script = _script(h.get("command"))
                if script in existing:
                    # Refresh how a managed hook is invoked. Matching by script
                    # name means the entry is found but never updated, so a fix
                    # to the command itself — routing it through .claude/py so
                    # it uses the interpreter that actually has PyYAML, without
                    # which gateway.deny is silently not enforced — reached new
                    # installs only. `_agentic_managed` marks the entry as
                    # installer-owned, which is the licence to rewrite it.
                    current = existing[script]
                    if current.get("command") != h.get("command"):
                        current["command"] = h["command"]
                        updated.append(f"{event}:{script}")
                    continue
                new_entry = {"hooks": [h]}
                if entry.get("matcher") is not None:
                    new_entry = {"matcher": entry["matcher"], "hooks": [h]}
                dst_entries.append(new_entry)
                existing[script] = h
                added.append(f"{event}:{h.get('command')}")
    if added or updated:
        dst_path.write_text(json.dumps(dst, indent=2) + "\n", encoding="utf-8")
        parts = []
        if added:
            parts.append(f"{len(added)} added")
        if updated:
            parts.append(f"{len(updated)} updated")
        info(f"settings.json: synced managed hooks ({', '.join(parts)})")


def _parse_models(agentic_yml_text: str) -> dict:
    """Parse the `models:` block of .agentic.yml with a line reader (no PyYAML,
    which the installer does not depend on). Returns {role: model_id}, skipping
    empty values (role: "" means 'inherit the session default')."""
    out: dict[str, str] = {}
    in_block = False
    for line in agentic_yml_text.splitlines():
        if re.match(r"^models:\s*(#.*)?$", line):
            in_block = True
            continue
        if in_block:
            if line and not line[0].isspace():  # dedent → block ended
                break
            m = re.match(r"^\s+([\w-]+):\s*(\S*)", line)
            if m:
                # Keep empty values too: role: "" means "inherit session default"
                # (don't stamp), which is distinct from a role being absent.
                out[m.group(1)] = m.group(2).strip('"').strip("'")
    return out


def _set_frontmatter_model(text: str, model: str) -> str:
    """Set/replace `model:` in a Markdown agent's YAML frontmatter."""
    m = re.match(r"(?s)^(---\n)(.*?\n)(---\n)", text)
    if not m:
        return text  # no frontmatter — leave untouched
    head, fm, tail = m.group(1), m.group(2), m.group(3)
    rest = text[m.end():]
    if re.search(r"(?m)^model:\s*.*$", fm):
        fm = re.sub(r"(?m)^model:\s*.*$", f"model: {model}", fm, count=1)
    elif re.search(r"(?m)^name:\s*.*$", fm):
        fm = re.sub(r"(?m)^(name:.*)$", r"\1\nmodel: " + model, fm, count=1)
    else:
        fm = f"model: {model}\n" + fm
    return head + fm + tail + rest


def stamp_agent_models(target: Path) -> None:
    """Write each agent's configured model into its frontmatter from .agentic.yml.

    Claude Desktop honors a subagent's frontmatter `model:` but IGNORES the
    invocation-time model override that dispatch_plan.py relies on — so without
    this every agent runs on the session model there, not its configured role
    model. Stamping makes Desktop honor role models. In the CLI, an explicit
    invocation model (complexity routing) still overrides frontmatter, so dynamic
    per-task routing is preserved. .agentic.yml stays the single source of truth;
    templates ship model-agnostic and this derives the frontmatter per install."""
    ayml = target / ".claude" / ".agentic.yml"
    agents_dir = target / ".claude" / "agents"
    if not ayml.exists() or not agents_dir.is_dir():
        return
    models = _parse_models(ayml.read_text(encoding="utf-8"))
    if not models:
        return
    default = models.get("default", "")
    stamped = 0
    for md in sorted(agents_dir.glob("*.md")):
        # explicit role entry wins (incl. "" = inherit → skip); else the default
        model = models[md.stem] if md.stem in models else default
        if not model:  # "" → inherit session default; don't pin a model
            continue
        text = md.read_text(encoding="utf-8")
        updated = _set_frontmatter_model(text, model)
        if updated != text:
            md.write_text(updated, encoding="utf-8")
            stamped += 1
    if stamped:
        info(f"stamped model: into {stamped} agent frontmatter(s) from .agentic.yml models:")


def resolve_interpreter(target: Path) -> str:
    """The interpreter to launch the MCP server with: project venv, else this one.

    Same order as `.claude/py`, which the commands go through. The two differ on
    purpose in *when* they resolve: `py` is committed, so it must resolve per
    call rather than carry one developer's path; `.mcp.json` is gitignored and
    regenerated per install, so an absolute path is both safe and better here —
    Claude Code spawns an MCP server directly rather than through a shell, so a
    `sh .claude/py` indirection would add a shell dependency that native Windows
    does not have.
    """
    names = ("bin/python", "Scripts/python.exe")
    for venv in (".venv", "venv", ".env"):
        for name in names:
            p = target / venv / name
            if p.is_file():
                # NOT p.resolve(): a venv's bin/python is a symlink to the base
                # interpreter, and resolving it hands back exactly the Python
                # that does not have the venv's site-packages. `target` is
                # already absolute, so this path is too.
                return str(p)
    return sys.executable


def stamp_mcp_interpreter(target: Path) -> None:
    """Point agentic_mcp at a real interpreter instead of the name `python3`.

    `python3` is not on PATH on native Windows outside the Store build, so the
    retrieve/get_symbol server simply never started there. Only rewritten while
    the value is still the template default, so a user who pinned their own
    interpreter keeps it.
    """
    p = target / ".mcp.json"
    if not p.is_file():
        return
    try:
        cfg = json.loads(p.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return
    srv = (cfg.get("mcpServers") or {}).get("agentic_mcp")
    if not isinstance(srv, dict) or srv.get("command") not in ("python3", "python"):
        return
    srv["command"] = resolve_interpreter(target)
    p.write_text(json.dumps(cfg, indent=2) + "\n", encoding="utf-8")
    info(f".mcp.json: agentic_mcp interpreter -> {srv['command']}")


def _merge_missing_section_keys(target: Path, section: str, keys: tuple[str, ...]) -> None:
    """Back-fill keys the template adds INSIDE an existing top-level block
    (e.g. `never_downgrade:` under `complexity_routing:`).

    The section-level upgrade only appends blocks that are absent wholesale, so a
    project seeded before a key existed keeps an outdated policy forever and
    silently. That matters for `never_downgrade`: without it, `low_cap` pulls
    gate-owning reviewers back down to the cheapest model on low-complexity
    tasks — the exact regression the key was added to prevent. For keys whose
    absent-default is already correct (`git.checkpoint_commits`) this is about
    discoverability: the behavior is right either way, but a key you cannot see
    in your own config is one you cannot turn off."""
    tpl_path = TEMPLATES_DIR / ".claude" / ".agentic.yml"
    dst_path = target / ".claude" / ".agentic.yml"
    if not tpl_path.exists() or not dst_path.exists():
        return
    tpl_text = tpl_path.read_text(encoding="utf-8")
    dst_text = dst_path.read_text(encoding="utf-8")
    lines = dst_text.splitlines(keepends=True)
    start = next((i for i, l in enumerate(lines)
                  if re.match(rf"^{re.escape(section)}:\s*(#.*)?$", l)), None)
    if start is None:
        return  # no block at all — the section-level append handles that case
    end = start
    for i in range(start + 1, len(lines)):
        if lines[i].strip() == "" or lines[i][:1].isspace():
            end = i
        else:
            break
    block = "".join(lines[start:end + 1])

    added = []
    for key in keys:
        if re.search(rf"^\s+{key}:", block, re.MULTILINE):
            continue
        m = re.search(rf"^(\s+{key}:.*)$", tpl_text, re.MULTILINE)
        if m:
            lines.insert(end + 1, m.group(1) + "\n")
            end += 1
            added.append(key)
    if added:
        dst_path.write_text("".join(lines), encoding="utf-8")
        info(f".agentic.yml: added missing {section} keys: {', '.join(added)}")


def _merge_missing_model_keys(target: Path) -> None:
    """Add role→model entries the template defines but the project's models: block
    is missing (e.g. roles added after the project was seeded), without touching
    the user's existing values. Fixes seed-once drift that would otherwise leave
    newer roles falling back to `default`."""
    tpl_path = TEMPLATES_DIR / ".claude" / ".agentic.yml"
    dst_path = target / ".claude" / ".agentic.yml"
    if not tpl_path.exists() or not dst_path.exists():
        return
    tpl_models = _parse_models(tpl_path.read_text(encoding="utf-8"))
    dst_text = dst_path.read_text(encoding="utf-8")
    dst_models = _parse_models(dst_text)
    missing = {k: v for k, v in tpl_models.items() if k not in dst_models}
    if not missing:
        return
    lines = dst_text.splitlines(keepends=True)
    start = next((i for i, l in enumerate(lines) if re.match(r"^models:\s*(#.*)?$", l)), None)
    if start is None:
        return
    last = start  # index of the last indented line in the models: block
    for i in range(start + 1, len(lines)):
        if lines[i].strip() == "":
            continue
        if lines[i][:1].isspace():
            last = i
        else:
            break
    ins = "".join(f"  {k}: {v}\n" for k, v in missing.items())
    dst_path.write_text("".join(lines[:last + 1]) + ins + "".join(lines[last + 1:]), encoding="utf-8")
    info(f".agentic.yml: added missing model roles: {', '.join(missing)}")


def warn_local_edits(target: Path) -> list[str]:
    """Name system files edited since install, BEFORE mirroring destroys them.

    System dirs are replaced wholesale on re-install, so a hand-edited agent
    disappears with no warning. `/agentic-doctor` reports it — but only if you
    think to run it beforehand, which is exactly when you do not know you need
    to. The manifest already records each file's installed hash, so the check
    costs nothing and belongs here, where it can still change the outcome.
    """
    mf_path = target / ".claude" / MANIFEST_NAME
    if not mf_path.is_file():
        return []
    try:
        files = (json.loads(mf_path.read_text(encoding="utf-8")) or {}).get("files") or {}
    except (json.JSONDecodeError, OSError):
        return []
    claude = target / ".claude"
    edited = []
    for rel, hashes in files.items():
        p = claude / rel
        if not p.is_file():
            continue
        try:
            if _hash_file(p) != hashes.get("cur"):
                edited.append(rel)
        except OSError:
            continue
    if edited:
        shown = ", ".join(sorted(edited)[:5])
        more = f" (+{len(edited) - 5} more)" if len(edited) > 5 else ""
        info(f"WARNING: {len(edited)} system file(s) edited since install: {shown}{more}")
        info("         these are being OVERWRITTEN now — system dirs are mirrored.")
        info("         To keep such a change, move it into the template repo.")
    return edited


def install(target: Path) -> None:
    target.mkdir(parents=True, exist_ok=True)
    warn_local_edits(target)   # before copy_templates, which destroys them
    copy_templates(target)
    sync_managed_hooks(target)
    stamp_mcp_interpreter(target)
    stamp_agent_models(target)
    write_manifest(target)  # after stamping — `cur` must hash the final files
    add_gitignore_block(target)
    info(f"install complete at {target}")
    info("next: pip install pyyaml fastembed sqlite-vec")
    info("then in Claude Code: /agentic-index  ->  /agentic-plan <goal>  ->  /agentic-build all")


# ---------- uninstall ----------

def strip_managed_settings(target: Path) -> None:
    p = target / ".claude" / "settings.json"
    if not p.exists():
        return
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        info(f"warning: could not parse {p}; leaving untouched")
        return

    hooks = data.get("hooks", {})
    for ev in list(hooks.keys()):
        kept = []
        for entry in hooks[ev]:
            new_hooks = [h for h in entry.get("hooks", []) if not h.get("_agentic_managed")]
            if new_hooks:
                entry["hooks"] = new_hooks
                kept.append(entry)
        if kept:
            hooks[ev] = kept
        else:
            del hooks[ev]
    if not hooks:
        data.pop("hooks", None)

    mcp = data.get("mcpServers", {})
    for name in list(mcp.keys()):
        if mcp[name].get("_agentic_managed"):
            del mcp[name]
    if not mcp:
        data.pop("mcpServers", None)

    if not data:
        p.unlink()
        info("removed empty settings.json")
    else:
        p.write_text(json.dumps(data, indent=2), encoding="utf-8")
        info("stripped managed entries from settings.json")


def remove_mcp_json_if_template(target: Path) -> None:
    """Remove .mcp.json only if it still matches the shipped template.

    Previously this keyed off the literal `REPLACE_WITH_` placeholders, which
    stopped working once credentials moved to ${VAR} expansion — every file
    would have looked edited and none would ever be removed. Comparing against
    the template is exact and does not depend on a secret being present.
    """
    p = target / ".mcp.json"
    if not p.exists():
        return
    tpl = TEMPLATES_DIR / ".mcp.json"
    try:
        cur = json.loads(p.read_text(encoding="utf-8"))
        ref = json.loads(tpl.read_text(encoding="utf-8")) if tpl.exists() else None
    except (json.JSONDecodeError, OSError):
        info(".mcp.json kept — could not parse it; delete manually if you want it gone.")
        return
    if ref is not None:
        # The interpreter is stamped per machine, so normalise it before compare.
        for c in (cur, ref):
            srv = (c.get("mcpServers") or {}).get("agentic_mcp")
            if isinstance(srv, dict):
                srv["command"] = "<stamped>"
    if ref is not None and cur == ref:
        p.unlink()
        info("removed .mcp.json (unchanged from the template)")
    else:
        info(".mcp.json kept — it has local changes. Delete manually if you want it gone.")


def remove_system_dirs(target: Path) -> None:
    claude = target / ".claude"
    if not claude.exists():
        return
    for name in SYSTEM_OWNED:
        p = claude / name
        if p.is_file():
            p.unlink()
            info(f"removed {name}")
        elif p.is_dir():
            shutil.rmtree(p)
            info(f"removed {name}/")
    state = claude / "state"
    if state.is_dir():
        info("kept state/ — run history, logs and vectors.db are not recoverable "
             "once deleted; remove .claude/state/ manually if you want it gone")
    if not any(claude.iterdir()):
        claude.rmdir()
        info("removed empty .claude/")


def remove_gitignore_block(target: Path) -> None:
    gi = target / ".gitignore"
    if not gi.exists():
        return
    new = GITIGNORE_RE.sub("", gi.read_text(encoding="utf-8"))
    if new.strip() == "":
        gi.unlink()
        info("removed empty .gitignore")
    else:
        gi.write_text(new, encoding="utf-8")
        info("stripped agentic block from .gitignore")


def uninstall(target: Path) -> None:
    strip_managed_settings(target)
    remove_system_dirs(target)
    remove_mcp_json_if_template(target)
    remove_gitignore_block(target)
    info(f"uninstall complete at {target}")


# ---------- upgrade-config ----------

def _upgrade_settings_json(target: Path) -> None:
    """Add new enabledMcpjsonServers entries from template; leave existing entries alone."""
    tpl_path = TEMPLATES_DIR / ".claude" / "settings.json"
    dst_path = target / ".claude" / "settings.json"
    if not tpl_path.exists() or not dst_path.exists():
        return
    try:
        tpl = json.loads(tpl_path.read_text(encoding="utf-8"))
        dst = json.loads(dst_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        info(f"warning: could not parse settings.json: {e} — skipping")
        return

    changed = False

    tpl_servers = tpl.get("enabledMcpjsonServers", [])
    dst_servers = dst.get("enabledMcpjsonServers", [])
    new_servers = [s for s in tpl_servers if s not in dst_servers]
    if new_servers:
        dst["enabledMcpjsonServers"] = dst_servers + new_servers
        changed = True
        info(f"settings.json: added to enabledMcpjsonServers: {new_servers}")

    if changed:
        dst_path.write_text(json.dumps(dst, indent=2) + "\n", encoding="utf-8")
    else:
        info("settings.json: already up to date")


def _upgrade_mcp_json(target: Path) -> None:
    """Add new mcpServers entries from template; leave existing entries alone."""
    tpl_path = TEMPLATES_DIR / ".mcp.json"
    dst_path = target / ".mcp.json"
    if not tpl_path.exists() or not dst_path.exists():
        return
    try:
        tpl = json.loads(tpl_path.read_text(encoding="utf-8"))
        dst = json.loads(dst_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        info(f"warning: could not parse .mcp.json: {e} — skipping")
        return

    tpl_servers = tpl.get("mcpServers", {})
    dst_servers = dst.get("mcpServers", {})

    added = []
    for name, config in tpl_servers.items():
        # Skip JSON comment/divider entries (string values, not server objects).
        if not isinstance(config, dict):
            continue
        if name not in dst_servers:
            dst_servers[name] = config
            added.append(name)

    if added:
        dst["mcpServers"] = dst_servers
        # Refresh the top-level comment so it stays accurate.
        if "_comment" in tpl:
            dst["_comment"] = tpl["_comment"]
        dst_path.write_text(json.dumps(dst, indent=2) + "\n", encoding="utf-8")
        info(f".mcp.json: added servers: {added}")
    else:
        info(".mcp.json: already up to date")


def _upgrade_agentic_yml(target: Path) -> None:
    """Replace only the available-skills comment block in .agentic.yml.

    Everything else (enabled_skills, embedding, gateway, etc.) is untouched
    because those are user configuration, not documentation.
    """
    tpl_path = TEMPLATES_DIR / ".claude" / ".agentic.yml"
    dst_path = target / ".claude" / ".agentic.yml"
    if not tpl_path.exists() or not dst_path.exists():
        return

    # Match from any comment line containing "Available built-in skills:" through
    # all subsequent comment lines, stopping just before "enabled_skills:".
    block_re = re.compile(r"(#[^\n]*Available built-in skills:[^\n]*\n(?:#[^\n]*\n)*)(?=enabled_skills:)", re.DOTALL)

    tpl_text = tpl_path.read_text(encoding="utf-8")
    dst_text = dst_path.read_text(encoding="utf-8")

    tpl_m = block_re.search(tpl_text)
    dst_m = block_re.search(dst_text)

    if not tpl_m:
        return
    if not dst_m:
        info(".agentic.yml: skills comment block not found (file may be customized) — skipping; add rest-openapi to the backend list manually if needed")
    elif tpl_m.group(1) == dst_m.group(1):
        info(".agentic.yml: skills block already up to date")
    else:
        dst_text = dst_text[: dst_m.start(1)] + tpl_m.group(1) + dst_text[dst_m.end(1):]
        dst_path.write_text(dst_text, encoding="utf-8")
        info(".agentic.yml: updated available-skills comment block")

    # Append any top-level section the template defines and this config lacks.
    #
    # This was four copy-pasted blocks naming one section each, which is why
    # config is seed-once and never healed for anything nobody remembered to add
    # a block for: `risk_profile`, `design` and `skill_groups` shipped and never
    # reached an existing install. One of the four searched for `maestro:`, a
    # section the template does not define — it had been silently doing nothing.
    #
    # Reading the section list off the template means a new section is upgraded
    # by existing, not by remembering to add a block here.
    dst_text = dst_path.read_text(encoding="utf-8")
    for name in _top_level_sections(tpl_text):
        if re.search(rf"^{re.escape(name)}:", dst_text, re.MULTILINE):
            continue
        block = _section_block(tpl_text, name)
        if not block:
            continue
        dst_text = dst_text.rstrip() + "\n\n" + block.rstrip() + "\n"
        dst_path.write_text(dst_text, encoding="utf-8")
        info(f".agentic.yml: added {name}: section")


def _top_level_sections(text: str) -> list[str]:
    """Top-level `key:` names, in file order."""
    return re.findall(r"^([a-z_][\w-]*):", text, re.MULTILINE)


def _section_block(text: str, name: str) -> str:
    """A section plus the comment lines immediately above it.

    The comments are the part that makes a block usable — `risk_profile:` copied
    without them is four keys with no statement of what `data_sensitivity` or
    `compliance` accept. The old per-section regexes started at the key and
    dropped them.
    """
    m = re.search(rf"^{re.escape(name)}:.*?(?=^[a-z_][\w-]*:|\Z)",
                  text, re.DOTALL | re.MULTILINE)
    if not m:
        return ""
    lines = text[:m.start()].splitlines()
    lead = []
    for line in reversed(lines):
        if line.startswith("#"):
            lead.append(line)
        elif line.strip() == "" and not lead:
            continue  # blank line between the previous block and the comments
        else:
            break
    return ("\n".join(reversed(lead)) + "\n" if lead else "") + m.group(0)


def upgrade_config(target: Path) -> None:
    _upgrade_settings_json(target)
    _upgrade_mcp_json(target)
    _upgrade_agentic_yml(target)
    stamp_mcp_interpreter(target)   # heal installs seeded with the name `python3`
    _merge_missing_model_keys(target)    # heal seed-once drift in models: block
    _merge_missing_section_keys(target, "complexity_routing", ("never_downgrade",))
    _merge_missing_section_keys(target, "git", ("checkpoint_commits",))
    stamp_agent_models(target)           # re-apply role models after the merge/edit
    write_manifest(target)               # …and re-record, since stamping may have changed files
    info(f"upgrade-config complete at {target}")


# ---------- cli ----------

def main() -> None:
    ap = argparse.ArgumentParser(description="Agentic Development Workflow installer.")
    ap.add_argument("--target", default=os.getcwd(), help="Project directory (default: cwd).")
    ap.add_argument("--uninstall", action="store_true", help="Remove managed entries.")
    ap.add_argument(
        "--upgrade-config",
        action="store_true",
        help="Merge new template defaults into existing config files "
             "(settings.json, .mcp.json, .agentic.yml). "
             "Adds new keys; never overwrites existing values.",
    )
    args = ap.parse_args()

    target = Path(args.target).resolve()
    if args.uninstall:
        uninstall(target)
    elif args.upgrade_config:
        upgrade_config(target)
    else:
        install(target)


if __name__ == "__main__":
    main()
